title:             Computer Science Blog
email:             cgbotta6336@yahoo.com
description:       Blog Prototype
author:            Colton Botta
baseurl:           "/ComputerScience"
url:               "http://cgbotta.github.io"

# Social Profiles
twitter_username:  colton_botta
github_username:   cgbotta
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
